#!/usr/bin/env python3
"""
import_doi_enrichment.py  --  Add DOI-sourced property statements to existing
                               Series (Q4) and Chapter (Q6) Wikibase items.

Workflow (two-run pattern)
--------------------------
Run 1  -- Bootstrap (no property_map.json present):
  Creates the five new DOI properties in Wikibase, writes their PIDs to
  outputs/property_map.json, then exits.  Review the map before continuing.

Run 2+  -- Import:
  Reads outputs/enrichment.xml (generated by csv_to_enrichment_xml.py).
  For each <item>, adds the new property statements via wbcreateclaim /
  wbsetreference API calls (does NOT reload the full item, so existing
  sitelinks are never touched).
  Skips statements whose property+value already exists on the item.

New properties (created on bootstrap)
--------------------------------------
  Publisher (DOI)        string   -- publisher name from Crossref DOI metadata
  ISBN Electronic (DOI)  string   -- electronic ISBN-13
  ISBN Print (DOI)       string   -- print ISBN-13
  Licence URL (DOI)      url      -- licence URL (Series items only)
  Abstract (DOI)         string   -- abstract text (Series items only)

Existing reference properties (used as provenance snaks, never recreated)
--------------------------------------------------------------------------
  P17  reference URL      url      -- source URL of the Crossref record
  P18  date accessed      time     -- date the record was accessed
  P19  source version     string   -- data provider label (e.g. Crossref)

Environment variables (.env or shell)
--------------------------------------
  WIKIBASE_URL   (default: http://localhost:8080)
  MW_API_URL     (default: {WIKIBASE_URL}/w/api.php)
  SPARQL_URL     (default: http://localhost:9999/bigdata/sparql)
  WB_USER        (default: admin)
  WB_PASSWORD    required

Optional control variables
---------------------------
  DRY_RUN=true   print actions without writing to Wikibase
  LIMIT=N        process only the first N items
  OFFSET=N       skip the first N items

Usage
-----
  # Bootstrap: create properties
  python import_doi_enrichment.py --bootstrap

  # Import (requires outputs/property_map.json from bootstrap)
  python import_doi_enrichment.py

  # Dry-run import (no writes)
  DRY_RUN=true python import_doi_enrichment.py

  # Process a subset
  OFFSET=0 LIMIT=10 python import_doi_enrichment.py
"""

import argparse
import json
import os
import sys
import time
import xml.etree.ElementTree as ET
from pathlib import Path

import requests as _requests

# ---------------------------------------------------------------------------
# Optional .env loading
# ---------------------------------------------------------------------------
try:
    from dotenv import load_dotenv
    _env_dir = Path(__file__).resolve().parent
    while _env_dir != _env_dir.parent:
        if (_env_dir / ".env").exists():
            load_dotenv(_env_dir / ".env")
            break
        _env_dir = _env_dir.parent
except ImportError:
    pass

# ---------------------------------------------------------------------------
# wikibaseintegrator imports  (used only for bootstrap)
# ---------------------------------------------------------------------------
try:
    from wikibaseintegrator import WikibaseIntegrator, wbi_login
    from wikibaseintegrator.wbi_config import config as wbi_config
    from wikibaseintegrator.wbi_helpers import search_entities
except ImportError:
    sys.exit(
        "wikibaseintegrator not found.\n"
        "Install with:  pip install wikibaseintegrator\n"
    )

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
WIKIBASE_URL = os.getenv("WIKIBASE_URL", "http://localhost:8080")
MW_API_URL   = os.getenv("MW_API_URL",   f"{WIKIBASE_URL}/w/api.php")
SPARQL_URL   = os.getenv("SPARQL_URL",   "http://localhost:9999/bigdata/sparql")
WB_USER      = os.getenv("WB_USER",      "admin")
WB_PASSWORD  = os.getenv("WB_PASSWORD",  "")

DRY_RUN = os.getenv("DRY_RUN", "false").lower() == "true"
OFFSET  = int(os.getenv("OFFSET", "0"))
LIMIT   = int(os.getenv("LIMIT",  "0"))

BASE_DIR      = Path(__file__).parent
XML_PATH      = BASE_DIR / "outputs" / "enrichment.xml"
PROP_MAP_PATH = BASE_DIR / "outputs" / "property_map.json"
LOG_PATH      = BASE_DIR / "outputs" / "import_log.json"

# Fixed reference property PIDs (already exist, not created by bootstrap)
P_REFERENCE_URL  = "P17"   # url
P_DATE_ACCESSED  = "P18"   # time
P_SOURCE_VERSION = "P19"   # string

# New properties to create in bootstrap (label, description, wikibase-datatype)
NEW_PROPERTIES = [
    (
        "Publisher (DOI)",
        "Publisher name sourced from Crossref DOI metadata",
        "string",
    ),
    (
        "ISBN Electronic (DOI)",
        "Electronic ISBN-13 sourced from Crossref DOI metadata",
        "string",
    ),
    (
        "ISBN Print (DOI)",
        "Print ISBN-13 sourced from Crossref DOI metadata",
        "string",
    ),
    (
        "Licence URL (DOI)",
        "Licence URL sourced from Crossref DOI metadata",
        "url",
    ),
    (
        "Abstract (DOI)",
        "Abstract text sourced from Crossref DOI metadata",
        "string",
    ),
]

# ---------------------------------------------------------------------------
# Bootstrap helpers  (wikibaseintegrator)
# ---------------------------------------------------------------------------

def connect_wbi() -> WikibaseIntegrator:
    """Authenticate with wbi (used for bootstrap only)."""
    if not WB_PASSWORD:
        sys.exit("WB_PASSWORD is not set.  Add it to .env or export it.")
    wbi_config["MEDIAWIKI_API_URL"] = MW_API_URL
    wbi_config["SPARQL_ENDPOINT_URL"] = SPARQL_URL
    wbi_config["WIKIBASE_URL"] = WIKIBASE_URL
    login = wbi_login.Clientlogin(user=WB_USER, password=WB_PASSWORD)
    return WikibaseIntegrator(login=login)


def find_property(label: str) -> str | None:
    """Return the PID of the first property whose English label matches exactly."""
    results = search_entities(
        search_string=label,
        search_type="property",
        language="en",
        max_results=10,
    )
    for res in results:
        if res.get("label", "").strip().lower() == label.strip().lower():
            return res["id"]
    return None


def create_property(wbi: WikibaseIntegrator, label: str, description: str, datatype: str) -> str:
    """Create a new Wikibase property and return its PID."""
    prop = wbi.property.new()
    prop.labels.set(language="en", value=label)
    prop.descriptions.set(language="en", value=description)
    prop.datatype = datatype
    prop.write()
    return prop.id


# ---------------------------------------------------------------------------
# Import helpers  (raw Wikibase API via requests)
# ---------------------------------------------------------------------------

def connect_session() -> _requests.Session:
    """Return an authenticated requests.Session using action=login."""
    if not WB_PASSWORD:
        sys.exit("WB_PASSWORD is not set.  Add it to .env or export it.")
    session = _requests.Session()
    r = session.get(
        MW_API_URL,
        params={"action": "query", "meta": "tokens", "type": "login", "format": "json"},
    )
    r.raise_for_status()
    token = r.json()["query"]["tokens"]["logintoken"]
    r2 = session.post(
        MW_API_URL,
        data={
            "action":     "login",
            "lgname":     WB_USER,
            "lgpassword": WB_PASSWORD,
            "lgtoken":    token,
            "format":     "json",
        },
    )
    r2.raise_for_status()
    result = r2.json()["login"]["result"]
    if result != "Success":
        sys.exit(f"Login failed: {result}")
    return session


def get_csrf_token(session: _requests.Session) -> str:
    """Return a fresh CSRF edit token."""
    r = session.get(
        MW_API_URL,
        params={"action": "query", "meta": "tokens", "format": "json"},
    )
    r.raise_for_status()
    return r.json()["query"]["tokens"]["csrftoken"]


def get_existing_values(session: _requests.Session,
                        qid: str, pids: list[str]) -> dict[str, set]:
    """Return {pid: {value_str, ...}} for existing claims on the item."""
    r = session.get(
        MW_API_URL,
        params={"action": "wbgetentities", "ids": qid, "props": "claims", "format": "json"},
    )
    r.raise_for_status()
    claims = r.json()["entities"].get(qid, {}).get("claims", {})
    result: dict[str, set] = {pid: set() for pid in pids}
    for pid in pids:
        for claim in claims.get(pid, []):
            try:
                dv = claim["mainsnak"]["datavalue"]["value"]
                if isinstance(dv, str):
                    result[pid].add(dv)
            except (KeyError, TypeError):
                pass
    return result


def create_claim(session: _requests.Session, qid: str, pid: str,
                 value: str, token: str) -> str:
    """Create a value claim on the item; return its GUID."""
    r = session.post(
        MW_API_URL,
        data={
            "action":   "wbcreateclaim",
            "entity":   qid,
            "snaktype": "value",
            "property": pid,
            "value":    json.dumps(value),
            "token":    token,
            "format":   "json",
        },
    )
    r.raise_for_status()
    data = r.json()
    if "error" in data:
        raise RuntimeError(f"wbcreateclaim: {data['error']}")
    return data["claim"]["id"]


def add_reference(session: _requests.Session, guid: str,
                  ref_url: str, date_str: str, provider: str, token: str) -> None:
    """Attach a Crossref provenance reference block to an existing claim."""
    snaks: dict = {}
    if ref_url:
        snaks[P_REFERENCE_URL] = [{
            "snaktype":  "value",
            "property":  P_REFERENCE_URL,
            "datavalue": {"type": "string", "value": ref_url},
        }]
    if date_str:
        snaks[P_DATE_ACCESSED] = [{
            "snaktype":  "value",
            "property":  P_DATE_ACCESSED,
            "datavalue": {
                "type": "time",
                "value": {
                    "time":          f"+{date_str}T00:00:00Z",
                    "timezone":      0,
                    "before":        0,
                    "after":         0,
                    "precision":     11,
                    "calendarmodel": "http://www.wikidata.org/entity/Q1985727",
                },
            },
        }]
    if provider:
        snaks[P_SOURCE_VERSION] = [{
            "snaktype":  "value",
            "property":  P_SOURCE_VERSION,
            "datavalue": {"type": "string", "value": provider},
        }]
    if not snaks:
        return
    r = session.post(
        MW_API_URL,
        data={
            "action":    "wbsetreference",
            "statement": guid,
            "snaks":     json.dumps(snaks),
            "token":     token,
            "format":    "json",
        },
    )
    r.raise_for_status()
    data = r.json()
    if "error" in data:
        raise RuntimeError(f"wbsetreference: {data['error']}")


# ---------------------------------------------------------------------------
# Bootstrap: create properties
# ---------------------------------------------------------------------------

def bootstrap(wbi: WikibaseIntegrator) -> None:
    """Create all five DOI properties and save their PIDs to property_map.json."""
    print("\n=== Bootstrap mode ===")
    print("Checking / creating DOI enrichment properties...\n")

    prop_map: dict[str, str] = {}

    for label, description, datatype in NEW_PROPERTIES:
        existing_pid = find_property(label)
        if existing_pid:
            print(f"  FOUND   {existing_pid}  {label}")
            prop_map[label] = existing_pid
        elif DRY_RUN:
            print(f"  DRY_RUN would create property: {label!r} ({datatype})")
            prop_map[label] = "P??"
        else:
            pid = create_property(wbi, label, description, datatype)
            print(f"  CREATED {pid}  {label}")
            prop_map[label] = pid
            time.sleep(0.5)

    if not DRY_RUN:
        PROP_MAP_PATH.parent.mkdir(exist_ok=True)
        PROP_MAP_PATH.write_text(
            json.dumps(prop_map, indent=2, ensure_ascii=False),
            encoding="utf-8",
        )
        print(f"\nProperty map saved to: {PROP_MAP_PATH}")

    print("\nProperty map:")
    for label, pid in prop_map.items():
        print(f"  {pid}  {label}")

    print("\nBootstrap complete.")
    if not DRY_RUN:
        print(f"Review {PROP_MAP_PATH.name} then run without --bootstrap to import.")


# ---------------------------------------------------------------------------
# Import: add claims to existing items via direct API calls
# ---------------------------------------------------------------------------

def import_enrichment(session: _requests.Session) -> None:
    """Parse enrichment.xml and add property statements to existing Wikibase items.

    Uses wbcreateclaim + wbsetreference directly so that existing sitelinks on
    items are never loaded or re-saved (avoiding sitelink-validation errors).
    """
    if not XML_PATH.exists():
        sys.exit(
            f"XML not found: {XML_PATH}\n"
            "Run  python csv_to_enrichment_xml.py  first."
        )
    if not PROP_MAP_PATH.exists():
        sys.exit(
            f"Property map not found: {PROP_MAP_PATH}\n"
            "Run  python import_doi_enrichment.py --bootstrap  first."
        )

    prop_map: dict[str, str] = json.loads(PROP_MAP_PATH.read_text(encoding="utf-8"))
    all_pids = list(prop_map.values())
    print(f"Loaded property map ({len(prop_map)} properties): "
          + ", ".join(f"{v}={k}" for k, v in prop_map.items()))

    tree = ET.parse(XML_PATH)
    all_items = tree.getroot().findall("item")

    items = all_items[OFFSET:]
    if LIMIT:
        items = items[:LIMIT]

    total = len(items)
    print(f"Parsed {len(all_items)} items from {XML_PATH.name}")
    print(f"Processing {total}  (offset={OFFSET}, limit={LIMIT or 'all'})")
    if DRY_RUN:
        print("** DRY_RUN mode -- no writes will be made **")
    print()

    ok_count    = 0
    error_count = 0
    log: list[dict] = []

    # Pre-fetch a CSRF token (refreshed every 50 items to avoid expiry)
    csrf_token = "" if DRY_RUN else get_csrf_token(session)

    for idx, item_el in enumerate(items, start=1):
        qid        = item_el.get("qid")
        item_type  = item_el.get("type")
        item_label = item_el.get("label")

        print(f"[{idx}/{total}] {qid} ({item_type}) {item_label[:60]} ...", end=" ", flush=True)

        # Refresh token every 50 items
        if not DRY_RUN and idx % 50 == 1 and idx > 1:
            csrf_token = get_csrf_token(session)

        try:
            # Fetch existing claim values for deduplication
            if DRY_RUN:
                existing: dict[str, set] = {pid: set() for pid in all_pids}
            else:
                existing = get_existing_values(session, qid, all_pids)

            stmt_log: list[dict] = []
            added    = 0
            skipped  = 0

            for stmt_el in item_el.findall("statement"):
                prop_label = stmt_el.get("prop")
                datatype   = stmt_el.get("datatype")   # "string" or "url"
                value      = stmt_el.get("value")

                pid = prop_map.get(prop_label)
                if not pid or pid == "P??":
                    print(f"\n  WARNING: no PID for '{prop_label}', skipping.")
                    continue

                # Duplicate check
                if value in existing.get(pid, set()):
                    stmt_log.append({
                        "prop": prop_label, "pid": pid,
                        "status": "skipped_duplicate",
                    })
                    skipped += 1
                    continue

                # Parse reference snaks from the XML
                ref_url = date_str = provider = ""
                ref_el  = stmt_el.find("reference")
                if ref_el is not None:
                    for snak in ref_el.findall("ref"):
                        spid = snak.get("pid")
                        sval = snak.get("value")
                        if spid == P_REFERENCE_URL:
                            ref_url  = sval
                        elif spid == P_DATE_ACCESSED:
                            date_str = sval
                        elif spid == P_SOURCE_VERSION:
                            provider = sval

                if DRY_RUN:
                    print(f"\n    DRY_RUN  {pid} {prop_label} = {value[:70]!r}")
                    stmt_log.append({
                        "prop": prop_label, "pid": pid,
                        "value": value[:80], "status": "dry_run",
                    })
                    added += 1
                    continue

                # Create claim then attach reference
                guid = create_claim(session, qid, pid, value, csrf_token)
                add_reference(session, guid, ref_url, date_str, provider, csrf_token)
                existing[pid].add(value)   # prevent duplicate on re-runs within same item

                stmt_log.append({
                    "prop": prop_label, "pid": pid,
                    "value": value[:80], "status": "added",
                })
                added += 1
                time.sleep(0.15)   # polite pause between API calls

            status = "dry_run" if DRY_RUN else "ok"
            print(f"{status} (+{added} added, {skipped} skipped)")

            log.append({
                "qid":        qid,
                "type":       item_type,
                "label":      item_label,
                "statements": stmt_log,
                "status":     status,
            })
            ok_count += 1

        except Exception as exc:
            error_count += 1
            print(f"ERROR: {exc}")
            log.append({
                "qid":    qid,
                "label":  item_label,
                "status": "error",
                "error":  str(exc),
            })

        time.sleep(0.2)

    # ---------------------------------------------------------------------------
    # Summary
    # ---------------------------------------------------------------------------
    print()
    print("=== Finished ===")
    print(f"  OK      : {ok_count}")
    print(f"  Errors  : {error_count}")

    if not DRY_RUN:
        LOG_PATH.parent.mkdir(exist_ok=True)
        LOG_PATH.write_text(
            json.dumps(log, indent=2, ensure_ascii=False), encoding="utf-8"
        )
        print(f"  Log     : {LOG_PATH}")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Add DOI bibliographic properties to existing Wikibase items."
    )
    parser.add_argument(
        "--bootstrap",
        action="store_true",
        help="Create the five DOI properties (run once before import).",
    )
    args = parser.parse_args()

    if args.bootstrap:
        wbi = connect_wbi()
        bootstrap(wbi)
    else:
        session = connect_session()
        import_enrichment(session)


if __name__ == "__main__":
    main()
